puts "... creating Answers 🔖"

all_questions = Question.ids

answer_list = [
                ["Longer if the vehicle is traveling at a higher speed.", "dd" ],
                ["Longer on a wet road than on a dry road", "dd" ],
                ["Longer if the vehicle is loaded.", "dd" ],
                ["If the road is clear for a long distance and can be done so without obstructing traffic.", "dd" ],
                ["In any manner as long as you use your indicator in time.", "dd" ],
                ["If the road is clear of traffic for a short distance.", "dd" ],
                ["60", "dd" ],
                ["45", "dd" ],
                ["30", "dd" ],
                ["Indicates that is is going to turn right.", "dd" ],
                ["Drives on the right hand side of the road with a shoulder where you can pass.", "dd" ],
                ["Drives in a town in the right-hand lane with two lanes in the same direction.", "dd" ],
                ["45", "dd" ],
                ["100", "dd" ],
                ["150", "dd" ],
                ["Switch on your indicator.", "dd" ],
                ["Check the bling spot", "dd" ],
                ["Looking the mirror", "dd" ],
                ["There is not enough space in the intersection to turn right without blocking other traffic", "dd" ],
                ["The vehicle in front of you wants to turn right and the road is wide enough to pass on the left-hand side", "dd" ],
                ["The robot (traffic signal) is yellow and you are already in the intersection", "dd" ],
                ["Pedestrians, who are already crossing the road when the red man signal starts showing, have right of way.", "dd" ],
                ["You can pass another vehicle waiting to turn right on its left side by going off the road.", "dd" ],
                ["You can stop in to off load passengers.", "dd" ],
                ["Stop and wait for the light to change to green before you go.", "dd" ],
                ["stop and go only if it is safe to do so.", "dd" ],
                ["Look out for road block as the light show you a police stop.", "dd" ],
                ["Call the local traffic department to report it", "dd" ],
                ["60", "dd" ],
                ["80", "dd" ],
                ["100", "dd" ],
                ["As fast as the other vehicle’s in the area", "dd" ],
                ["When is rains and you cannot see vehicles 100 m in front of you.", "dd" ],
                ["You tow another vehicle with a tow-bar.", "dd" ],
                ["At any time of day when you cannot see persons and vehicles 150 m in front of you.", "dd" ],
                ["Not pass any vehicle on the left-hand side.", "dd" ],
                ["Pass another vehicle at any place on the left hand side if it is turning right.", "dd" ],
                ["Pass another vehicle turning right,on the left-hand side without driving on the shoulder of the road.", "dd" ],
                ["Stop without swerving", "dd" ],
                ["swerve and stop next to it", "dd" ],
                ["swerve and pass", "dd" ],
                ["There must be someone with you in the vehicle with the same driving licence.", "dd" ],
                ["You are not allowed to drive on a freeway.", "dd" ],
                ["No passengers are allowed with you in the vehicle.", "dd" ],
                ["When you switch the emergency lights of your motor vehicle on.", "dd" ],
                ["When a traffic officer orders you to do so.", "dd" ],
                ["Under no circumstances.", "dd" ],
                ["If your vehicle has seat belts in the rear, it must be worn", "dd" ],
                ["You need not wear seat belt when reversing.", "dd" ],
                ["Children younger than 14 years need not wear seat belts.", "dd" ],
                ["If the front seat has a belt, your only passenger may not sit in the back", "dd" ],
                ["You already have a licence that authorizes the driving of the same vehicle class.", "dd" ],
                ["You are declared unfit to obtain a driving licence for a certain period and that period still prevails", "dd" ],
                ["Your licence was suspended temporarily and the suspension has not yet expired.", "dd" ],
                ["Opposite a vehicle, where the roadway is 10 m wide.", "dd" ],
                ["Where you are not allowed to park", "dd" ],
                ["5 m from a bridge", "dd" ],
                ["With a rope", "dd" ],
                ["With a tow-bar", "dd" ],
                ["On a trailer", "dd" ],
                ["0.75", "dd" ],
                ["1", "dd" ],
                ["1.5", "dd" ],
                ["When you are with in a traffic circle.", "dd" ],
                ["When you have stopped fist at a four way stop.", "dd" ],
                ["When you want to turn right at an intersection in a two way road.", "dd" ],
                ["Are nearing the top of a hill", "dd" ],
                ["Nearing a curve", "dd" ],
                ["Can only see 100 m in front of you because of smoke over the road.", "dd" ],
                ["With a rope", "dd" ],
                ["With a tow-bar", "dd" ],
                ["On a trailer", "dd" ],
                ["A motor car tows another motorcar with a rope and drive 40 km/h.", "dd" ],
                ["You tow another vehicle with a tow-bar.", "dd" ],
                ["A tractor tows a trailer with 10 passengers on it at a speed of 30km/h", "dd" ],
                ["Drinking and driving", "dd" ],
                ["Always be courteous and considerate towards fellow road users.", "dd" ],
                ["Do not exceed the speed limit.", "dd" ],
                ["Keep to the left side of the road as far as safe.", "dd" ],
                ["is always 120 km/m outside towns/cities?", "dd" ],
                ["can be determined by yourself if you look at the number on lanes which the road has", "dd" ],
                ["is shown to you by the signs next you the road", "dd" ],
                ["Slow down", "dd" ],
                ["Give other vehicle’s room to pass", "dd" ],
                ["Indicate your intensions and give the necessary signal in time", "dd" ],
                ["may use a little bit of alcohol for the shock", "dd" ],
                ["must check if anyone is injured", "dd" ],
                ["must immediately stop your vehicle", "dd" ],
                ["Switch on your indicator and change lanes.", "dd" ],
                [" Give the necessary signal after looking for other traffic, change lanes.", "dd" ],
                ["Take a selfie", "dd" ],
                ["Apply the brakes lightly and then change lanes.", "dd" ]
              ]

answer_list.map do |answer|
  Answer.create!(
    content: answer[0],
    explanation: answer[1]
    )
end
